version: 2
updates:
  - package-ecosystem: "github-actions"
    directories:
      - "/"
      - "/.github/actions/install-osmesa"
    schedule:
      interval: "weekly" # Options: daily, weekly, monthly
    open-pull-requests-limit: 10
